### ISSUE TITLE
UnboundLocalError: local variable 'keypoint_count' referenced before assignment

### ISSUE THREAD

**Issue by lin-fangzhou** [aaronWool/rcvpose#14]
(venv310) blab@blab-server:~/pporzz/rcvpose$ python main.py --root_dataset="/home/bimlab/pporzz/rcvpose/Datasets/6dPoseData/" --mode=test --demo_mode True
ape
Traceback (most recent call last):
  File "/home/bimlab/pporzz/rcvpose/main.py", line 70, in <module>
    trainer = Trainer(data, opts, vis)
  File "/home/bimlab/pporzz/rcvpose/train.py", line 25, in __init__
    self.Test()
  File "/home/bimlab/pporzz/rcvpose/train.py", line 194, in Test
    estimate_6d_pose_lm(self.opts)
  File "/home/bimlab/pporzz/rcvpose/AccumulatorSpace.py", line 518, in estimate_6d_pose_lm
    model_path = opts.model_dir + class_name+"_pt"+str(keypoint_count)+".pth.tar"
UnboundLocalError: local variable 'keypoint_count' referenced before assignment

I don't have any ideas on this issue. Can someone help me? Or give a hint?

**Comment by aaronWool** [comment]
Hi, this bug should be fixed now. Thanks for pointing this out!
