### ISSUE TITLE
Reference before assignment

### ISSUE THREAD

**Issue by neox395** [aaronWool/rcvpose#8]
https://github.com/aaronWool/rcvpose/blob/e25ff74cc02f3e70fcd2901fd0568f5c0be90022/AccumulatorSpace.py#L518

**Comment by lin-fangzhou** [comment]
May I ask if you have resolved this issue, which seems to be the same as what I encountered?

(venv310) blab@blab-server:~/pporzz/rcvpose$ python main.py --root_dataset="/home/bimlab/pporzz/rcvpose/Datasets/6dPoseData/" --mode=test --demo_mode False
ape
Traceback (most recent call last):
  File "/home/bimlab/pporzz/rcvpose/main.py", line 70, in <module>
    trainer = Trainer(data, opts, vis)
  File "/home/bimlab/pporzz/rcvpose/train.py", line 25, in __init__
    self.Test()
  File "/home/bimlab/pporzz/rcvpose/train.py", line 194, in Test
    estimate_6d_pose_lm(self.opts)
  File "/home/bimlab/pporzz/rcvpose/AccumulatorSpace.py", line 518, in estimate_6d_pose_lm
    model_path = opts.model_dir + class_name+"_pt"+str(keypoint_count)+".pth.tar"
UnboundLocalError: local variable 'keypoint_count' referenced before assignment

**Comment by tomole444** [comment]
The same here
